// Auto-generated types for RabbitMesh services
// Do not edit this file manually

/** Request type for login */
export interface LoginRequest {
  data: any;
}

/** Response type for login */
export interface LoginResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Request type for validateToken */
export interface ValidateTokenRequest {
  data: any;
}

/** Response type for validateToken */
export interface ValidateTokenResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Request type for refreshToken */
export interface RefreshTokenRequest {
  data: any;
}

/** Response type for refreshToken */
export interface RefreshTokenResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Request type for checkPermission */
export interface CheckPermissionRequest {
  data: any;
}

/** Response type for checkPermission */
export interface CheckPermissionResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Request type for logout */
export interface LogoutRequest {
  data: any;
}

/** Response type for logout */
export interface LogoutResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Response type for getCurrentUser */
export interface GetCurrentUserResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Request type for createOrder */
export interface CreateOrderRequest {
  data: any;
}

/** Response type for createOrder */
export interface CreateOrderResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Response type for getOrder */
export interface GetOrderResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Request type for updateOrder */
export interface UpdateOrderRequest {
  data: any;
}

/** Response type for updateOrder */
export interface UpdateOrderResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Response type for deleteOrder */
export interface DeleteOrderResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Response type for getUserOrders */
export interface GetUserOrdersResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Response type for getOrdersByStatus */
export interface GetOrdersByStatusResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Request type for confirmOrder */
export interface ConfirmOrderRequest {
  data: any;
}

/** Response type for confirmOrder */
export interface ConfirmOrderResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Request type for cancelOrder */
export interface CancelOrderRequest {
  data: any;
}

/** Response type for cancelOrder */
export interface CancelOrderResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Request type for createUser */
export interface CreateUserRequest {
  data: any;
}

/** Response type for createUser */
export interface CreateUserResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Response type for getUser */
export interface GetUserResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Request type for updateUser */
export interface UpdateUserRequest {
  data: any;
}

/** Response type for updateUser */
export interface UpdateUserResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Response type for deleteUser */
export interface DeleteUserResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Response type for listUsers */
export interface ListUsersResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

/** Response type for getUserByEmail */
export interface GetUserByEmailResponse {
  data?: any;
  success?: boolean;
  message?: string;
}

export interface ApiResponse {
  data?: any;
  success?: boolean;
  message?: string;
}
